import type { EnterprisePlan, EnterpriseProduct } from "./types";

export const ENTERPRISE_PRODUCTS: EnterpriseProduct[] = [
  { id: "cvfx", name: "Cuentas Virtuales + FX", driver: "TPV", unit: "USD" },
  { id: "payment-initiation", name: "Iniciación de Pagos", driver: "Transacciones", unit: "tx" },
  { id: "payouts", name: "Payouts", driver: "Payouts", unit: "payouts" },
];

export const ENTERPRISE_SEED: EnterprisePlan = {
  version: 1,
  modelStartMonth: "2027-03",
  horizonMonths: 36,
  clpPerUsd: 930,
  enterpriseStartingCashUsd: 0,
  consolidatedStartingCashUsd: 0,
  products: ENTERPRISE_PRODUCTS,
  clients: [
    { id: "xtransfer-pe", name: "XTransfer", country: "Perú", productId: "cvfx", goLiveMonth: "2027-03", status: "Planificado", owner: "Por asignar" },
    { id: "xtransfer-cl", name: "XTransfer", country: "Chile", productId: "cvfx", goLiveMonth: "2027-04", status: "Planificado", owner: "Por asignar" },
    { id: "xtransfer-br", name: "XTransfer", country: "Brasil", productId: "cvfx", goLiveMonth: "2027-07", status: "Planificado", owner: "Por asignar" },
    { id: "aguas-andinas", name: "Aguas Andinas", country: "Chile", productId: "payment-initiation", goLiveMonth: "2027-03", status: "Activo al inicio", owner: "Por asignar", priceClp: 70 },
    { id: "prontopaga-init", name: "ProntoPaga", country: "Chile", productId: "payment-initiation", goLiveMonth: "2027-03", status: "Activo al inicio", owner: "Por asignar", priceClp: 70 },
    { id: "prontopaga-payouts", name: "ProntoPaga", country: "Chile", productId: "payouts", goLiveMonth: "2027-08", status: "Estimación / editable", owner: "Por asignar", bancoEstadoMix: 0.6 },
  ],
  volumeSegments: [
    { id: "pe-0", clientId: "xtransfer-pe", fromMonth: 0, toMonth: 2, volume: 5_000_000, status: "Validado" },
    { id: "pe-3", clientId: "xtransfer-pe", fromMonth: 3, toMonth: 5, volume: 15_000_000, status: "Validado" },
    { id: "pe-6", clientId: "xtransfer-pe", fromMonth: 6, toMonth: 8, volume: 30_000_000, status: "Validado" },
    { id: "pe-9", clientId: "xtransfer-pe", fromMonth: 9, toMonth: 11, volume: 50_000_000, status: "Validado" },
    { id: "pe-12", clientId: "xtransfer-pe", fromMonth: 12, toMonth: 17, volume: null, status: "Por validar" },
    { id: "pe-18", clientId: "xtransfer-pe", fromMonth: 18, toMonth: 23, volume: null, status: "Por validar" },
    { id: "pe-24", clientId: "xtransfer-pe", fromMonth: 24, toMonth: 35, volume: null, status: "Por validar" },
    { id: "cl-0", clientId: "xtransfer-cl", fromMonth: 0, toMonth: 2, volume: 5_000_000, status: "Validado" },
    { id: "cl-3", clientId: "xtransfer-cl", fromMonth: 3, toMonth: 5, volume: 15_000_000, status: "Validado" },
    { id: "cl-6", clientId: "xtransfer-cl", fromMonth: 6, toMonth: 8, volume: 30_000_000, status: "Validado" },
    { id: "cl-9", clientId: "xtransfer-cl", fromMonth: 9, toMonth: 11, volume: 50_000_000, status: "Validado" },
    { id: "cl-12", clientId: "xtransfer-cl", fromMonth: 12, toMonth: 17, volume: null, status: "Por validar" },
    { id: "cl-18", clientId: "xtransfer-cl", fromMonth: 18, toMonth: 23, volume: null, status: "Por validar" },
    { id: "cl-24", clientId: "xtransfer-cl", fromMonth: 24, toMonth: 35, volume: null, status: "Por validar" },
    { id: "br-0", clientId: "xtransfer-br", fromMonth: 0, toMonth: 2, volume: 5_000_000, status: "Validado" },
    { id: "br-3", clientId: "xtransfer-br", fromMonth: 3, toMonth: 5, volume: 10_000_000, status: "Validado" },
    { id: "br-6", clientId: "xtransfer-br", fromMonth: 6, toMonth: 11, volume: 25_000_000, status: "Validado" },
    { id: "br-12", clientId: "xtransfer-br", fromMonth: 12, toMonth: 17, volume: null, status: "Por validar" },
    { id: "br-18", clientId: "xtransfer-br", fromMonth: 18, toMonth: 23, volume: null, status: "Por validar" },
    { id: "br-24", clientId: "xtransfer-br", fromMonth: 24, toMonth: 35, volume: null, status: "Por validar" },
    { id: "aa-0", clientId: "aguas-andinas", fromMonth: 0, toMonth: 35, volume: 70_000, status: "Validado" },
    { id: "pp-init-0", clientId: "prontopaga-init", fromMonth: 0, toMonth: 35, volume: 650_000, status: "Validado" },
    { id: "pp-payouts-0", clientId: "prontopaga-payouts", fromMonth: 0, toMonth: 35, volume: 900_000, status: "Validado" },
  ],
  costs: [],
  assumptions: {
    cvfxDefaultSpread: 0.002,
    paymentInitiationPriceClp: 70,
    paymentInitiationProviderCostClp: 40,
    payoutPriceBancoEstadoClp: 463,
    payoutPriceOtherBanksClp: 198,
    payoutApiCostClp: 10,
    payoutCostBancoEstadoClp: 423,
    payoutCostOtherBanksClp: 129,
    payoutDefaultBancoEstadoMix: 0.6,
    cvfxProviders: [
      { country: "Perú", swiftCostUsd: 50, localRailCostUsd: 0.13, payoutCostUsd: 15, localTicketUsd: 2_000, steadySwiftTicketUsd: 500_000, payoutsPerMillionTpv: 1.2 },
      { country: "Chile", swiftCostUsd: 25, localRailCostUsd: 0.2, payoutCostUsd: 2, localTicketUsd: 2_000, steadySwiftTicketUsd: 500_000, payoutsPerMillionTpv: 1.4 },
      { country: "Brasil", swiftCostUsd: 20, localRailCostUsd: 0.034, payoutCostUsd: 0.034, localTicketUsd: 2_000, steadySwiftTicketUsd: 1_500_000, payoutsPerMillionTpv: 0 },
    ],
  },
  updatedAt: "2026-08-20T00:00:00.000Z",
};
